apiVersion: v1
entries:
  redis:
  - apiVersion: v1
    appVersion: 4.0.14
    created: 2019-04-29T17:06:09.560472643+08:00
    description: Open source, advanced key-value store. It is often referred to as
      a data structure server since keys can contain strings, hashes, lists, sets
      and sorted sets.
    digest: 76670c9a4b529592b08e25ca1947a0944077a1760cd1278971405cf85182d1de
    engine: gotpl
    home: http://redis.io/
    icon: https://bitnami.com/assets/stacks/redis/img/redis-stack-220x234.png
    keywords:
    - redis
    - keyvalue
    - database
    maintainers:
    - email: containers@bitnami.com
      name: Bitnami
    - email: cedric@desaintmartin.fr
      name: desaintmartin
    name: redis
    sources:
    - https://github.com/bitnami/bitnami-docker-redis
    urls:
    - redis-7.0.0.tgz
    version: 7.0.0
generated: 2019-04-29T17:06:09.557429515+08:00
